apiVersion: apps/v1
kind: Deployment
metadata:
  name: airport-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airport-app
  template:
    metadata:
      labels:
        app: airport-app
    spec:
      containers:
        - name: airport-app
          image: ranam093/assessment:4.0
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_BUCKET_NAME
